import Footer from '@/components/Footer/Footer'
import '../styles/globals.css'
import { AppProvider } from '@/context/AppContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <main>
            {children}
            <Footer />
          </main>
        </AppProvider>
      </body>
    </html>
  )
}
